### ISSUE TITLE
Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by 3x1l3** [EddyVerbruggen/nativescript-local-notifications-demo#1]
I'm getting an error trying to run the demo following the steps on the readme. I haven't modified the code at all. Here is the stack trace:

> TypeError: Cannot read property 'version' of undefined
>     at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:535:15)
>     at /usr/local/lib/node_modules/nativescript/lib/common/errors.js:123:33
>     at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
>     at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
>     at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:84:106
>     at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
>     at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
>     at /usr/local/lib/node_modules/nativescript/lib/common/yok.js:208:124
>     at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
>     at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
>     at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:51:55
>     at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
>     at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
>     at /usr/local/lib/node_modules/nativescript/lib/common/errors.js:123:33
>     at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
>     at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
>     - - - - -
>     at /usr/local/lib/node_modules/nativescript/lib/services/android-project-service.js:370:122
>     at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
>     at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
>     at /usr/local/lib/node_modules/nativescript/lib/services/android-project-service.js:81:54
>     at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
>     at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
>     at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:221:123
>     at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
>     at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
>     at /usr/local/lib/node_modules/nativescript/lib/common/helpers.js:224:36
>     at PlatformService.descriptor.value [as preparePlatformCore](/usr/local/lib/node_modules/nativescript/lib/common/helpers.js:191:24)
>     at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:182:26
>     at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
>     at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
>     at /usr/local/lib/node_modules/nativescript/lib/services/platform-service.js:270:50
>     at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)

Any help would be appreciated. Thanks

**Comment by EddyVerbruggen** [comment]
Are you using NativeScript 2.0.0? I tried that with the demo app.

**Comment by 3x1l3** [comment]
Yes I'm using NativeScript 2.0.0.

**Comment by EddyVerbruggen** [comment]
I don't see anything related to the plugin in your stacktrace. Does a new project without the plugin work correctly? And if so, can you add it as a plugin (not using the demo app) and build again?

**Comment by 3x1l3** [comment]
Building a blank project works. Building with the plugin yields this during build:

> Exception in thread "main" java.lang.IllegalArgumentException: Class com.tns.internal.AppBuilderCallback conflict: /Users/tangle/Sites/testExample/platforms/android/build/intermediates/classes/F0F1/debug and /Users/tangle/Sites/testExample/platforms/android/build/intermediates/classes/F0/debug
>     at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
>     at com.telerik.metadata.Builder.build(Builder.java:42)
>     at com.telerik.metadata.Generator.main(Generator.java:44)
> :buildMetadata FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':buildMetadata'.
  
  > Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.507 secs
Error: Command /Users/tangle/Sites/testExample/platforms/android/gradlew failed with exit code 1
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:535:15)
    at /usr/local/lib/node_modules/nativescript/lib/common/errors.js:123:33
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:84:106
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/yok.js:208:124
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:51:55
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/errors.js:123:33
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:534:10)
    - - - - -
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/child-process.js:91:38)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by EddyVerbruggen** [comment]
Doesn't ring a bell 💭 ❌ 

Does the same happen when adding a different plugin to a new project? Weird..

**Comment by 3x1l3** [comment]
Actually I tried adding it to the sample tutorial project from Native
script and it builds fine but I get a undefined variable when I try to
schedule a notification. Seems to be a js warning in the console though.

**Comment by 3x1l3** [comment]
Building for IOS on a blank project with just the plugin added works fine however... but building the demo app for IOS returns the same error as my original.

**Comment by kelvin-dev** [comment]
@all,
This is a Nativescript's critical bug ! Please have a look at below issue:
https://github.com/NativeScript/NativeScript/issues/2291

**Comment by leoacevedo** [comment]
No change in almost two years for this?

**Comment by EddyVerbruggen** [comment]
Not sure this is still relevant. Feel free to open a new issue, but please supply me with a github Project I can clone that reproduces the issue.
